CREATE OR REPLACE FUNCTION FN_ATUALIZA_SENHA(P_ID_USUARIO TEXT, P_NEW_SENHA TEXT)
RETURNS BOOLEAN AS $$
BEGIN
	UPDATE AUTENTIFICACAO
	SET SENHA = P_NEW_SENHA
	WHERE ID_USUARIO = UUID(P_ID_USUARIO);
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO ATUALIZAR SENHA DE USUARIO', SQLSTATE, SQLERRM, 'FN_ATUALIZA_SENHA', 'AUTENTIFICACAO', CURRENT_QUERY());
		RETURN FALSE;
END;