CREATE OR REPLACE FUNCTION 
FN_ATUALIZA_PRODUTO(P_ID_PRODUTO TEXT, P_NOME TEXT, P_DESCRICAO TEXT, 
					P_VALOR_BASE_DIARIA NUMERIC(16,2),P_VALOR_BASE_MENSAL NUMERIC(16,2),
					P_VALOR_PRODUTO NUMERIC(16,2), P_DATA_COMPRA TEXT)
RETURNS BOOLEAN AS $$
BEGIN
	UPDATE PRODUTOS
	SET NOME = P_NOME, DESCRICAO = P_DESCRICAO, VALOR_BASE_DIARIA = P_VALOR_BASE_DIARIA,
	VALOR_BASE_MENSAL = P_VALOR_BASE_MENSAL, VALOR_PRODUTO = P_VALOR_PRODUTO,
	DATA_COMPRA = P_DATA_COMPRA
	WHERE ID_PRODUTO = UUID(P_ID_PRODUTO);
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO ATUALIZAR PRODUTO', SQLSTATE, SQLERRM, 'FN_ATUALIZA_PRODUTO', 'PRODUTOS', CURRENT_QUERY());
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;

/*
SELECT FN_ATUALIZA_PRODUTO('8fa22a3c-da5e-4adb-abf1-12a909f44a84', 'Makita', 'Teste da FN_ATUALIZA_PRODUTO',
						  12.99, 150, 1200);
*/