CREATE OR REPLACE FUNCTION
    FN_ATIVA_USUARIO(P_CODE TEXT, P_USUARIO TEXT DEFAULT '')
    RETURNS BOOLEAN AS $$
BEGIN

    IF EXISTS (SELECT 1 FROM USUARIOS WHERE CODIGO_VERIFICACAO = UUID(P_CODE)) THEN
        UPDATE USUARIOS
        SET VERIFICADO = TRUE, ATIVO = TRUE, CODIGO_VERIFICACAO = NULL
        WHERE CODIGO_VERIFICACAO = UUID(P_CODE);
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO ATIVAR USUARIO', SQLSTATE, SQLERRM, 'FN_ATIVA_USUARIO', 'USUARIOS', CURRENT_QUERY(),P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
