CREATE OR REPLACE FUNCTION 
FN_APROVA_PRODUTO(P_ID_PRODUTO TEXT, P_MOTIVO TEXT,P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN	
	
	UPDATE PRODUTOS
	SET PUBLICADO = TRUE
	WHERE ID_PRODUTO = UUID(P_ID_PRODUTO);
	
	RETURN QUERY
	SELECT U.NOME, P.NOME, EMAIL 
	FROM USUARIOS U
	INNER JOIN PRODUTOS P
	ON U.ID_USUARIO = P.ID_USUARIO
	WHERE P.ID_USUARIO = UUID(P_ID_USUARIO);
	
	--RETURN P_ID_USUARIO;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO PUBLICAR PRODUTO', SQLSTATE, SQLERRM, 'FN_APROVA_PRODUTO', 'PRODUTOS', CURRENT_QUERY(),P_USUARIO);
		RETURN;
END;
$$ LANGUAGE PLPGSQL;