CREATE OR REPLACE FUNCTION
    FN_ATIVA_CADASTRO(P_TOKEN TEXT, P_USUARIO TEXT DEFAULT '')
    RETURNS BOOLEAN AS $$
BEGIN

    UPDATE USUARIOS
    SET VERIFICADO = TRUE, CODIGO_VERIFICACAO = NULL
    WHERE (CODIGO_VERIFICACAO = UUID(P_TOKEN));
    IF NOT FOUND THEN
        RETURN FALSE;
    ELSE
        RETURN TRUE;
    END IF;
        EXCEPTION WHEN OTHERS THEN
        PERFORM FN_REPORT_ERRO('ERRO AO ATIVAR CADASTRO', SQLSTATE, SQLERRM, 'FN_ATIVA_CADASTRO', 'USUARIOS', CURRENT_QUERY(),P_USUARIO);
        RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
