CREATE OR REPLACE  FUNCTION 
FN_CADASTRAR_ATUALIZA_CATEGORIA_PRODUTO(P_ID_PRODUTO UUID, P_CATEGORIAS TEXT)
RETURNS BOOLEAN AS $$
DECLARE A_CATEGORIAS TEXT[];
DECLARE C TEXT;
BEGIN	
	A_CATEGORIAS = STRING_TO_ARRAY(P_CATEGORIAS,',');
	
	DELETE FROM CATEGORIA_PRODUTO
	WHERE ID_PRODUTO = P_ID_PRODUTO;
	
	FOREACH C IN ARRAY A_CATEGORIAS
		LOOP
			INSERT INTO CATEGORIA_PRODUTO(ID_PRODUTO,ID_CATEGORIA)
			VALUES (P_ID_PRODUTO,C);
		END LOOP;
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO CADASTRAR CATEGORIA', SQLSTATE, SQLERRM, 'FN_CADASTRAR_CATEGORIA_PRODUTO', 'CATEGORIA_PRODUTO', CURRENT_QUERY());
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;