CREATE OR REPLACE  FUNCTION FN_CONFIRMA_ENCONTRO(P_ID_ALUGUEL TEXT, P_OK BOOLEAN, P_MOTIVO TEXT,P_USUARIO TEXT)
    RETURNS BOOLEAN AS $$
BEGIN

    UPDATE ALUGUEL_ENCONTRO
    SET ACEITE_LOCADOR = P_OK, OBSERVACAO_RECUSA = P_MOTIVO
    WHERE ID_ALUGUEL = UUID(P_ID_ALUGUEL);

    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO EFETUAR ALUGUEIS', SQLSTATE, SQLERRM, 'FN_EFETUA_ALUGUEL', 'ALUGUEIS', CURRENT_QUERY(), P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
