CREATE OR REPLACE FUNCTION 
FN_CANCELA_ALUGUEL(P_ID_ALUGUEL TEXT, P_ID_USUARIO TEXT, P_USUARIO TEXT DEFAULT '')
RETURNS BOOLEAN AS $$
BEGIN

	UPDATE ALUGUEIS A
	SET COD_STATUS_ALUGUEL = 
	CASE WHEN (UUID(P_ID_USUARIO) = ID_USUARIO)
		THEN 6 --Cancelado pelo locatário
		ELSE 5 --Cancelado pelo locador
	END
	WHERE (ID_ALUGUEL = UUID(P_ID_ALUGUEL))
	AND (UUID(P_ID_USUARIO) = ID_USUARIO OR (SELECT ID_USUARIO FROM PRODUTOS WHERE ID_PRODUTO = A.ID_PRODUTO) = UUID(P_ID_USUARIO));
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO CANCELAR ALUGUEL', SQLSTATE, SQLERRM, 'FN_CANCELA_ALUGUEL', 'ALUGUEIS', CURRENT_QUERY(),P_USUARIO);
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;