CREATE OR REPLACE FUNCTION FN_CONFIMA_RECUSA_CHK_DEVOLUCAO(P_ID_ALUGUEL TEXT, P_OK BOOLEAN, P_USUARIO TEXT DEFAULT '')
RETURNS BOOLEAN AS $$
BEGIN

    UPDATE aluguel_chk_devolucao
    SET ok_locador = P_OK
    WHERE id_aluguel = UUID(P_ID_ALUGUEL)
    AND ok_locador IS NULL;

    RETURN TRUE;

    EXCEPTION WHEN OTHERS THEN
        PERFORM FN_REPORT_ERRO('ERRO AO GRAVAR CHECKLIST DEVOLUÇÃO', SQLSTATE, SQLERRM, 'FN_GRVAVA_CHK_ENTREGA', 'FN_GRVAVA_CHK_DEVOLUCAO', CURRENT_QUERY(),P_USUARIO);
        RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
