CREATE OR REPLACE FUNCTION 
FN_ALUGUEL_PAGAMENTO(P_ID_ALUGUEL TEXT, P_USUARIO TEXT DEFAULT '')
RETURNS BOOLEAN AS $$
BEGIN

	UPDATE ALUGUEIS A
	SET COD_STATUS_ALUGUEL = 11
	WHERE (ID_ALUGUEL = UUID(P_ID_ALUGUEL));
	
	INSERT INTO ALUGUEL_HISTORICO(ID_ALUGUEL, COD_STATUS_ALUGUEL)
    SELECT ID_ALUGUEL,COD_STATUS_ALUGUEL
	FROM ALUGUEIS
	WHERE ID_ALUGUEL = UUID(P_ID_ALUGUEL);
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO CANCELAR ALUGUEL', SQLSTATE, SQLERRM, 'FN_CANCELA_ALUGUEL', 'ALUGUEIS', CURRENT_QUERY(),P_USUARIO);
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;