CREATE OR REPLACE FUNCTION FN_EFETUA_SAQUE_LOCADOR(P_ID_USUARIO TEXT, P_id_pagamento text)
    RETURNS BOOLEAN
AS $$
DECLARE
    PAGAMENTOS TEXT[];
    P TEXT;
BEGIN

    PAGAMENTOS = STRING_TO_ARRAY(P_id_pagamento,';');

    FOREACH P IN ARRAY PAGAMENTOS
        LOOP
            IF P <> '' THEN
                UPDATE saldo_locador
                SET sacado = TRUE
                WHERE id_pagamento = uuid(P);
            END IF;
        END LOOP;

    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO EFETUAR SAQUE', SQLSTATE, SQLERRM, 'FN_EFETUA_SAQUE_LOCADOR', 'SALDO_LOCADOR', CURRENT_QUERY(), P_ID_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
