CREATE OR REPLACE FUNCTION FN_EFETUA_ALUGUEL(P_ID_USUARIO TEXT, P_ID_PRODUTO TEXT, P_DATA_INICIO TEXT, P_DATA_FIM TEXT, P_VALOR_ALUGUEL DOUBLE PRECISION)
RETURNS BOOLEAN AS $$
BEGIN
	
	INSERT INTO ALUGUEIS(
	ID_USUARIO,
	ID_PRODUTO,
	DATA_INICIO,
	DATA_FIM,
	VALOR_ALUGUEL,
	VALOR_DEBITO)
	SELECT
	UUID(P_ID_USUARIO),
	UUID(P_ID_PRODUTO),
	TO_TIMESTAMP(P_DATA_INICIO,'YYYY-MM-DD HH24:MI:SS'),
	TO_TIMESTAMP(P_DATA_FIM,'YYYY-MM-DD HH24:MI:SS'),
	P_VALOR_ALUGUEL,
	(P_VALOR_ALUGUEL - (P_VALOR_ALUGUEL * SUM(VLR_TAXA)))
	FROM TAXAS;
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO EFETUAR ALUGUEIS', SQLSTATE, SQLERRM, 'FN_EFETUA_ALUGUEL', 'ALUGUEIS', CURRENT_QUERY());
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;