CREATE OR REPLACE FUNCTION 
FN_FOTO_USUARIO(P_ID_USUARIO TEXT, P_FOTO BYTEA, P_USUARIO TEXT DEFAULT '')
RETURNS BOOLEAN AS $$
BEGIN

	UPDATE USUARIOS
	SET CAPA_FOTO = P_FOTO
	WHERE ID_USUARIO = UUID(P_ID_USUARIO);
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO ATUALIZAR FOTO DE USUARIOS', SQLSTATE, SQLERRM, 'FN_FOTO_USUARIO', 'USUARIOS', CURRENT_QUERY(), P_USUARIO);
		RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;