CREATE OR REPLACE FUNCTION FN_GRVAVA_FOTO_CHK_ENTREGA(P_ID_ALUGUEL TEXT, P_FOTO BYTEA, P_USUARIO TEXT DEFAULT '')
    RETURNS BOOLEAN AS $$
BEGIN
    update aluguel_chk_entrega
    set foto_produto = P_FOTO
    WHERE id_aluguel = UUID(P_ID_ALUGUEL);
    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO GRAVAR CHECKLIST DEVOLUÇÃO', SQLSTATE, SQLERRM, 'FN_GRVAVA_FOTO_CHK_ENTREGA', 'FN_GRVAVA_CHK_DEVOLUCAO', CURRENT_QUERY(),P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
