CREATE OR REPLACE FUNCTION FN_GRAVA_HISTORICO_ALUGUEL() 
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO ALUGUEL_HISTORICO(ID_ALUGUEL, COD_STATUS_ALUGUEL)
	VALUES (NEW.ID_ALUGUEL, NEW.COD_STATUS_ALUGUEL)
	RETURN NEW;
END;
$$
