CREATE OR REPLACE FUNCTION FN_GRVAVA_CHK_DEVOLUCAO(P_ID_ALUGUEL TEXT, P_DESCRICAO TEXT, P_USUARIO TEXT DEFAULT '')
    RETURNS BOOLEAN AS $$
BEGIN
    INSERT INTO aluguel_chk_devolucao(ID_ALUGUEL, DESCRICAO)
    VALUES(UUID(P_ID_ALUGUEL),P_DESCRICAO);
    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO GRAVAR CHECKLIST DEVOLUÇÃO', SQLSTATE, SQLERRM, 'FN_GRVAVA_CHK_ENTREGA', 'FN_GRVAVA_CHK_DEVOLUCAO', CURRENT_QUERY(),P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;