/*************************************************************
Função/Procedimento: FN_INSERIR_USUARIO.
Objetivo: Responsável pelo cadastro das informações de usuário.
Parâmetros: Nome, CPF, Email, Sexo, Data_Nascimento, Senha, Login(null), Telefone(null), Celular(null).
Exemplo de execução:
START TRANSACTION;
SELECT FN_INSERIR_USUARIO('Roberval', '11111222223', 'piter_parq@alugo.com', 'Masculino', 
						  '2020-01-05', 'aaabbbccc', 'feijão_queimado', '1122334455', '1122334433');
COMMIT;
**************************************************************/

CREATE OR REPLACE FUNCTION 
FN_INSERIR_USUARIO_MIN(P_NOME TEXT, P_EMAIL VARCHAR(50), P_LOGIN VARCHAR(50), P_SENHA TEXT, 
						P_CPF VARCHAR(14), P_CELULAR VARCHAR(20))
RETURNS SETOF RECORD AS $$
DECLARE P_ID_USUARIO UUID;
DECLARE OK BOOLEAN = FALSE;
DECLARE P_DATA_NASCIMENTO DATE;
BEGIN

	BEGIN
		INSERT INTO USUARIOS(
		NOME,
		CPF,
		EMAIL,
		CELULAR)
		VALUES(
		P_NOME,
		P_CPF,
		LOWER(P_EMAIL),
		P_CELULAR)
		RETURNING ID_USUARIO INTO P_ID_USUARIO;
	
		EXCEPTION WHEN OTHERS THEN
			PERFORM FN_REPORT_ERRO('ERRO AO INSERIR O USUARIO', sqlstate, sqlerrm, 'FN_INSERIR_USUARIO_MIN', 'USUARIOS', CURRENT_QUERY());
			RETURN;
	END;
		
	SELECT FN_INSERIR_LOGIN(CAST(P_ID_USUARIO AS TEXT), P_SENHA, LOWER(P_LOGIN)) INTO OK;
	
	IF NOT OK THEN
		DELETE FROM USUARIOS
		WHERE ID_USUARIO = P_ID_USUARIO;
		RETURN;
		
	ELSE
		BEGIN
			RETURN QUERY SELECT *FROM FN_RETORNA_USUARIO(CAST(P_ID_USUARIO AS TEXT))
				AS T(ID_USUARIO TEXT, NOME TEXT, EMAIL TEXT, LOGIN TEXT, CPF TEXT,
					CELULAR TEXT, DATA_NASCIMENTO TEXT, CEP TEXT, LOGRADOURO TEXT, 
					COMPLEMENTO TEXT, BAIRRO TEXT, NUMERO TEXT, ATIVO BOOLEAN, CAPA_FOTO BYTEA);
				
			EXCEPTION WHEN OTHERS THEN
				PERFORM FN_REPORT_ERRO('ERRO NO RETORNO USUARIO', SQLSTATE, SQLERRM, 'FN_INSERIR_USUARIO_MIN', 'USUARIO', CURRENT_QUERY());
				RETURN;	
			END;
	END IF;
		
	EXCEPTION WHEN OTHERS THEN
		DELETE FROM USUARIOS
		WHERE ID_USUARIO = P_ID_USUARIO;
		RETURN;
		
		DELETE FROM AUTENTIFICACAO
		WHERE ID_USUARIO = P_ID_USUARIO;
		RETURN;
		
		PERFORM FN_REPORT_ERRO('ERRO AO CADASTRAR USUARIO', SQLSTATE, SQLERRM, 'FN_INSERIR_USUARIO_MIN', 'USUARIO', CURRENT_QUERY());
		RETURN;	
		
END;
$$  LANGUAGE PLPGSQL