CREATE OR REPLACE FUNCTION
    FN_INSERIR_USUARIO_MIN(P_NOME TEXT, P_EMAIL VARCHAR(50), P_LOGIN VARCHAR(50), P_SENHA TEXT,
                           P_CPF VARCHAR(14), P_CELULAR VARCHAR(20), P_VERIFICACAO TEXT)
    RETURNS BOOLEAN AS $$
DECLARE P_ID_USUARIO UUID;
DECLARE OK BOOLEAN = FALSE;
BEGIN

    BEGIN
        INSERT INTO USUARIOS(
            NOME,
            CPF,
            EMAIL,
            CELULAR,
			CODIGO_VERIFICACAO
			)
        VALUES(
          P_NOME,
          P_CPF,
          LOWER(P_EMAIL),
          P_CELULAR,
		  UUID(P_VERIFICACAO)
		  )
        RETURNING ID_USUARIO INTO P_ID_USUARIO;

    EXCEPTION WHEN OTHERS THEN
        PERFORM FN_REPORT_ERRO('ERRO AO INSERIR O USUARIO', sqlstate, sqlerrm, 'FN_INSERIR_USUARIO_MIN', 'USUARIOS', CURRENT_QUERY(),P_USUARIO);
        RETURN FALSE;
    END;

    SELECT FN_INSERIR_LOGIN(CAST(P_ID_USUARIO AS TEXT), P_SENHA, LOWER(P_LOGIN)) INTO OK;

    IF NOT OK THEN
        DELETE FROM USUARIOS
        WHERE ID_USUARIO = P_ID_USUARIO;
        RETURN FALSE;

    ELSE
        RETURN TRUE;
    END IF;

EXCEPTION WHEN OTHERS THEN
    DELETE FROM USUARIOS
    WHERE ID_USUARIO = P_ID_USUARIO;
    PERFORM FN_REPORT_ERRO('ERRO AO CADASTRAR USUARIO', SQLSTATE, SQLERRM, 'FN_INSERIR_USUARIO_MIN', 'USUARIO', CURRENT_QUERY(),P_USUARIO);
    RETURN FALSE;

END;
$$  LANGUAGE PLPGSQL;
