CREATE OR REPLACE FUNCTION FN_REPORT_ERRO_BACKEND(P_CONTROLLER TEXT, P_METODO TEXT, P_ENDPOINT TEXT, P_USUARIO TEXT, P_MESSAGE TEXT, P_STACK_TRACE TEXT)
RETURNS BOOLEAN AS $$
BEGIN

    INSERT INTO LOG.LOG_ERROS_BACKEND(CONTROLLER, METODO, ENDPOINT, USUARIO, MESSAGE, STACK_TRACE)
    VALUES (P_CONTROLLER, P_METODO, P_ENDPOINT, P_USUARIO, P_MESSAGE, P_STACK_TRACE);
	
	RETURN TRUE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO SALVAR LOGS DO BACKEND', SQLSTATE, SQLERRM, 'FN_REPORT_ERRO_BACKEND', 'LOG_ERROS_BACKEND', CURRENT_QUERY(), P_USUARIO);
	RETURN FALSE;

END;
$$ LANGUAGE plpgsql
