CREATE OR REPLACE FUNCTION FN_RETORNA_ALUGUEIS_NOTIFICACAO_INICIO(OP INTEGER, P_USUARIO TEXT DEFAULT '')
    RETURNS SETOF RECORD AS $$
BEGIN
    SET TIMEZONE='AMERICA/SAO_PAULO';

    DROP TABLE IF EXISTS TEMP_ENTREGA;
    CREATE TEMP TABLE TEMP_ENTREGA AS
    SELECT
        CAST(A.ID_ALUGUEL AS TEXT) IDALUGUEL,
        CAST(P.NOME AS TEXT) PRODUTONOME,
        CAST(LOCADOR.NOME AS TEXT) LOCADORNOME,
        CAST(LOCADOR.EMAIL AS TEXT) LOCADOREMAIL,
        CAST(LOCADOR.CELULAR AS TEXT) LOCADORCELULAR,
        CAST(LOCATARIO.NOME AS TEXT) LOCATARIONOME,
        CAST(LOCATARIO.EMAIL AS TEXT) LOCATARIOEMAIL,
        CAST(LOCATARIO.CELULAR AS TEXT) LOCATARIOCELULAR
    FROM ALUGUEIS A
             INNER JOIN USUARIOS LOCATARIO
                        ON A.ID_USUARIO = LOCATARIO.ID_USUARIO
             INNER JOIN PRODUTOS P
                        ON P.ID_PRODUTO = A.ID_PRODUTO
             INNER JOIN USUARIOS LOCADOR
                        ON P.ID_USUARIO = LOCADOR.ID_USUARIO
             INNER JOIN aluguel_encontro AD
                        ON AD.ID_ALUGUEL = A.ID_ALUGUEL
    WHERE COD_STATUS_ALUGUEL = 1
      AND NOT notificacao_envio
      AND ((OP = 1 AND TO_CHAR(data_entrega - INTERVAL '2' HOUR,'YYYY-MM-DD HH24') = TO_CHAR(CURRENT_TIMESTAMP,'YYYY-MM-DD HH24'))
        OR (OP = 2));

    UPDATE aluguel_encontro
    SET notificacao_envio = TRUE
    WHERE (ID_ALUGUEL IN (SELECT IDALUGUEL FROM TEMP_ENTREGA));

    RETURN QUERY
        SELECT *FROM TEMP_ENTREGA;

    DROP TABLE IF EXISTS TEMP_ENTREGA;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR ALUGUEIS', SQLSTATE, SQLERRM, 'FN_RETORNA_ALUGUEIS_NOTIFICACAO_INICIO', 'ALUGUEIS', CURRENT_QUERY(),P_USUARIO);
    RETURN;

END;
$$ LANGUAGE PLPGSQL;
