CREATE OR REPLACE FUNCTION FN_RETORNA_ALUGUEIS_NOTIFICACAO_FIM(P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN
	SET TIMEZONE='AMERICA/SAO_PAULO';
	
	UPDATE ALUGUEL_DETALHE
	SET ENVIADO = TRUE
	WHERE TO_CHAR(DATA_HORA - INTERVAL '2' HOUR,'YYYY-MM-DD HH24') = TO_CHAR(CURRENT_TIMESTAMP,'YYYY-MM-DD HH24')
	AND NOT ENVIADO;
	
	RETURN QUERY
	SELECT 
	CAST(A.ID_ALUGUEL AS TEXT) IDALUGUEL,
	CAST(P.NOME AS TEXT) PRODUTONOME,
	CAST(LOCADOR.NOME AS TEXT) LOCADORNOME, 
	CAST(LOCADOR.EMAIL AS TEXT) LOCADOREMAIL,
	CAST(LOCATARIO.NOME AS TEXT) LOCATARIONOME, 
	CAST(LOCATARIO.EMAIL AS TEXT) LOCATARIOEMAIL
	FROM ALUGUEIS A
	INNER JOIN USUARIOS LOCATARIO
		ON A.ID_USUARIO = LOCATARIO.ID_USUARIO
	INNER JOIN PRODUTOS P
		ON P.ID_PRODUTO = A.ID_PRODUTO
	INNER JOIN USUARIOS LOCADOR
		ON P.ID_USUARIO = LOCADOR.ID_USUARIO
	INNER JOIN ALUGUEL_DETALHE AD
		ON AD.ID_ALUGUEL = A.ID_ALUGUEL
	WHERE COD_STATUS_ALUGUEL = 2
	AND AD.TIPO = 2
	AND NOT ENVIADO
	AND TO_CHAR(DATA_HORA - INTERVAL '2' HOUR,'YYYY-MM-DD HH24') = TO_CHAR(CURRENT_TIMESTAMP,'YYYY-MM-DD HH24');
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR ALUGUEIS', SQLSTATE, SQLERRM, 'FN_RETORNA_ALUGUEIS_NOTIFICACAO_FIM', 'ALUGUEIS', CURRENT_QUERY(),P_USUARIO);

END;
$$ LANGUAGE PLPGSQL;