CREATE OR REPLACE FUNCTION FN_RETORNA_LOG_BACKEND_CONTROLLER_MES(P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN

	RETURN QUERY
	SELECT CAST(CONTROLLER AS TEXT), CAST(COUNT(1) AS INT) QUANTIDADE, CAST(FN_RETORNA_ERROS_MES_BACKEND_TO_STRING(CONTROLLER) AS TEXT)
	FROM LOG.LOG_ERROS_BACKEND
	GROUP BY CONTROLLER;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR ERROS', SQLSTATE, SQLERRM, 'FN_RETORNA_LOG_BACKEND_MES', 'LOG_ERROS_BACKEND', CURRENT_QUERY(),P_USUARIO);
		RETURN;
END;
$$ LANGUAGE PLPGSQL;