CREATE OR REPLACE FUNCTION FN_RETORNA_SENHA(P_ID_USUARIO TEXT, P_USUARIO TEXT DEFAULT '')
    RETURNS TEXT AS $$
BEGIN
        SELECT
            CAST(A.PASSWORD AS TEXT)
        FROM AUTENTIFICACAO A
        WHERE A.ID_USUARIO = UUID(P_ID_USUARIO);

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO RETORNAR SENHA', sqlstate, sqlerrm, 'FN_RETORNA_SENHA', 'AUTENTIFICACAO', CURRENT_QUERY(), P_USUARIO);
    RETURN '';
END;
$$  LANGUAGE plpgsql
