CREATE OR REPLACE FUNCTION 
FN_RETORNA_CATEGORIAS(P_ID_PRODUTO UUID)
RETURNS TEXT AS $$
DECLARE A_CATEGORIAS TEXT[];
DECLARE T_CATEGORIA TEXT;
DECLARE C TEXT;
BEGIN	

	/*
	A_CATEGORIAS = (SELECT ARRAY_AGG(ID_CATEGORIA) 
				  FROM CATEGORIA_PRODUTO
				  WHERE ID_PRODUTO = P_ID_PRODUTO);
				  
	IF A_CATEGORIAS IS NULL THEN
		RETURN '';
	END IF;

	FOREACH C IN ARRAY A_CATEGORIAS
		LOOP
			IF T_CATEGORIA IS NULL THEN 
				T_CATEGORIA = C;
			ELSE 
				T_CATEGORIA = T_CATEGORIA || ',' || C;
			END IF;
		END LOOP;
	*/
	T_CATEGORIA = (SELECT ARRAY_TO_STRING(ARRAY_AGG(C.ID_CATEGORIA),',') || ';' 
					|| ARRAY_TO_STRING(ARRAY_AGG(DESCRICAO),',')
					FROM CATEGORIA_PRODUTO CP
					INNER JOIN CATEGORIA C
					ON CP.ID_CATEGORIA = C.ID_CATEGORIA
					WHERE ID_PRODUTO = P_ID_PRODUTO);
	RETURN T_CATEGORIA;
END;
$$ LANGUAGE PLPGSQL;