CREATE OR REPLACE FUNCTION FN_RETORNA_DATAS_ALUGADAS(P_ID_PRODUTO TEXT)
RETURNS SETOF RECORD AS $$	
BEGIN 
	RETURN QUERY 
	SELECT TO_CHAR(DATA_INICIO,'YYYY-MM-DD'), TO_CHAR(DATA_FIM,'YYYY-MM-DD')
	FROM ALUGUEIS A
	WHERE A.ID_PRODUTO = UUID(P_ID_PRODUTO)
	AND TO_DATE(TO_CHAR(DATA_FIM,'YYYY-MM-DD'),'YYYY-MM-DD') >= CURRENT_DATE;
	
END;
$$ LANGUAGE PLPGSQL;