CREATE OR REPLACE FUNCTION FN_RETORNA_RESUMO_SALDO_LOCADOR(P_ID_USUARIO text)
    RETURNS DECIMAL(18,2)
    LANGUAGE PLPGSQL
AS
$$
DECLARE P_SALDO DECIMAL(18,2);
BEGIN

    SELECT CAST(SUM(VALOR)AS DECIMAL(18,2)) VALOR
    INTO P_SALDO
    FROM SALDO_LOCADOR
    WHERE ID_LOCADOR = uuid(P_ID_USUARIO)
      AND NOT SACADO;

    IF P_SALDO IS NULL THEN
        RETURN 0.00;
    ELSE
        RETURN P_SALDO;
    END IF;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO RETORNAR RESUMO EXTRATO LOCADOR', SQLSTATE, SQLERRM, 'FN_RETORNA_RESUMO_SALDO_LOCADOR', 'SALDO_LOCADOR', CURRENT_QUERY(), P_ID_USUARIO);
    RETURN FALSE;
END;
$$;
