CREATE OR REPLACE FUNCTION FN_RETORNA_LOG_MES(P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN

	RETURN QUERY
	SELECT CAST(PROCEDURE AS TEXT), CAST(COUNT(1) AS INT) QUANTIDADE, CAST(FN_RETORNA_ERROS_MES_TO_STRING(PROCEDURE) AS TEXT)
	FROM LOG.LOG_ERROS
	GROUP BY PROCEDURE;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR ERROS', SQLSTATE, SQLERRM, 'FN_RETORNA_LOG_MES', 'LOG_ERROS', CURRENT_QUERY(),P_USUARIO);
		RETURN;
END;
$$ LANGUAGE PLPGSQL;