CREATE OR REPLACE FUNCTION FN_RETORNA_CHK_ENTREGA(P_ID_ALUGUEL TEXT, P_USUARIO TEXT DEFAULT '')
    RETURNS SETOF RECORD AS $$
BEGIN

    RETURN QUERY
        SELECT
        CAST(ID_ALUGUEL AS TEXT),
        DESCRICAO,
        foto_produto,
        OK_LOCAdor,
		MOTIVO_RECUSA
    FROM ALUGUEL_CHK_ENTREGA
    WHERE ID_ALUGUEL = UUID(P_ID_ALUGUEL)
	ORDER BY DATA_INCLUSAO DESC
	LIMIT 1;
EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR CHECKLIST ENTREGA', SQLSTATE, SQLERRM, 'FN_RETORNA_CHK_ENTREGA', 'ALUGUEL_CHK_ENTREGA', CURRENT_QUERY(),P_USUARIO);
    RETURN;
END;
$$ LANGUAGE PLPGSQL;
