CREATE OR REPLACE FUNCTION
    FN_RETORNA_DADOS_LOCADOR_LOCATARIO(P_ID_ALUGUEL TEXT, P_USUARIO TEXT DEFAULT '')
	RETURNS SETOF RECORD AS $$
BEGIN

RETURN QUERY
	SELECT CAST(A.ID_ALUGUEL AS TEXT),
	cast(P.NOME as text),
	cast(LOCADOR.NOME as text), 
	cast(LOCADOR.EMAIL as text),
	cast(LOCADOR.CELULAR as text), 
	cast(LOCATARIO.NOME as text), 
	cast(LOCATARIO.EMAIL as text), 
	cast(LOCATARIO.CELULAR as text)
	FROM ALUGUEIS A
	INNER JOIN PRODUTOS P
		ON P.ID_PRODUTO = A.ID_PRODUTO
	INNER JOIN USUARIOS LOCADOR
		ON P.ID_USUARIO = LOCADOR.ID_USUARIO
	INNER JOIN USUARIOS LOCATARIO
		ON LOCATARIO.ID_USUARIO = A.ID_USUARIO
	WHERE A.ID_ALUGUEL = UUID(P_ID_ALUGUEL);

		EXCEPTION WHEN OTHERS THEN
			PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR DADOS', SQLSTATE, SQLERRM, 'FN_RETORNA_DADOS_LOCADOR_LOCATARIO', 'PRODUTOS/USUARIOS/ALUGUEL', CURRENT_QUERY(),P_USUARIO);
			RETURN;

END;
$$ LANGUAGE PLPGSQL;