CREATE OR REPLACE FUNCTION 
FN_REJEITA_PRODUTO(P_ID_PRODUTO TEXT, P_MOTIVO TEXT,P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN	
	
	INSERT INTO PRODUTOS_REJEITADOS(
		ID_PRODUTO,
		ID_USUARIO, 
		NOME,
		DESCRICAO_CURTA,
		DESCRICAO, 
		VALOR_BASE_DIARIA, 
		VALOR_BASE_MENSAL,
		VALOR_PRODUTO,
		DATA_COMPRA,
		USUARIO_OPERACAO,
		MOTIVO)
	SELECT 
		UUID(P_ID_PRODUTO)
		ID_USUARIO, 
		NOME, 
		DESCRICAO_CURTA,
		DESCRICAO,
		VALOR_BASE_DIARIA,
		VALOR_BASE_MENSAL,
		VALOR_PRODUTO,
		DATA_COMPRA,
		P_USUARIO,
		P_MOTIVO
		FROM PRODUTOS
		WHERE ID_PRODUTO = UUID(P_ID_PRODUTO);
		
	DELETE FROM CATEGORIA_PRODUTO
	WHERE ID_PRODUTO = UUID(P_ID_PRODUTO);
	
	DELETE FROM PRODUTOS
	WHERE ID_PRODUTO = UUID(P_ID_PRODUTO);
	
	RETURN QUERY
	SELECT U.NOME, P.NOME, EMAIL 
	FROM USUARIOS U
	INNER JOIN PRODUTOS_REJEITADOS P
	ON U.ID_USUARIO = P.ID_USUARIO
	WHERE P.ID_USUARIO = UUID(P_ID_USUARIO);
	
	--RETURN P_ID_USUARIO;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO REJEITAR PRODUTO', SQLSTATE, SQLERRM, 'FN_REJEITA_PRODUTO', 'PRODUTOS_REJEITADOS', CURRENT_QUERY(),P_USUARIO);
		RETURN;
END;
$$ LANGUAGE PLPGSQL;