CREATE OR REPLACE FUNCTION FN_RETORNA_LOG_BACKEND_METODOS_MES(P_CONTROLLER TEXT,P_USUARIO TEXT DEFAULT '')
RETURNS SETOF RECORD AS $$
BEGIN

	RETURN QUERY
	SELECT CAST(METODO AS TEXT), CAST(ENDPOINT AS TEXT), CAST(COUNT(1) AS INT) QUANTIDADE, CAST(FN_RETORNA_ERROS_MES_BACKEND_METODOS_TO_STRING(METODO, P_CONTROLLER) AS TEXT)
	FROM LOG.LOG_ERROS_BACKEND
	WHERE CONTROLLER = P_CONTROLLER
	GROUP BY METODO, ENDPOINT;
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO SELECIONAR ERROS', SQLSTATE, SQLERRM, 'FN_RETORNA_LOG_BACKEND_METODOS_MES', 'LOG_ERROS_BACKEND', CURRENT_QUERY(),P_USUARIO);
		RETURN;
END;
$$ LANGUAGE PLPGSQL;