CREATE OR REPLACE  FUNCTION  FN_SALVA_URL_PAGAMENTO(P_ID_ALUGUEL TEXT,P_URL_PAGAMENTO TEXT, P_USUARIO TEXT)
    RETURNS BOOLEAN AS $$
BEGIN

    UPDATE ALUGUEIS
    SET url_pagamento = P_URL_PAGAMENTO
    WHERE id_aluguel = uuid(P_ID_ALUGUEL);

    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO EFETUAR ALUGUEIS', SQLSTATE, SQLERRM, 'FN_SALVA_URL_PAGAMENTO', 'ALUGUEIS', CURRENT_QUERY(), P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;