CREATE OR REPLACE FUNCTION 
FN_STATUS_ALUGUEL(P_ID_ALUGUEL TEXT, P_STATUS INT, P_USUARIO TEXT DEFAULT '')
RETURNS VOID AS $$
BEGIN

	UPDATE ALUGUEIS A
	SET COD_STATUS_ALUGUEL = P_STATUS
	WHERE (ID_ALUGUEL = UUID(P_ID_ALUGUEL));
	
	INSERT INTO ALUGUEL_HISTORICO(ID_ALUGUEL, COD_STATUS_ALUGUEL)
    SELECT ID_ALUGUEL,COD_STATUS_ALUGUEL
	FROM ALUGUEIS
	WHERE ID_ALUGUEL = UUID(P_ID_ALUGUEL);
	
	EXCEPTION WHEN OTHERS THEN
		PERFORM FN_REPORT_ERRO('ERRO AO ALTERAR STATUS ALUGUEL', SQLSTATE, SQLERRM, 'FN_STATUS_ALUGUEL', 'ALUGUEIS', CURRENT_QUERY(),P_USUARIO);
END;
$$ LANGUAGE PLPGSQL;