CREATE OR REPLACE FUNCTION
    FN_SALVA_DETALHE_ALUGUEL(P_ID_ALUGUEL TEXT,P_CEP TEXT,P_LOGRADOURO TEXT, P_BAIRRO TEXT,
                             P_DESCRICAO TEXT, P_DATA_HORA TEXT, P_TIPO INT, P_USUARIO TEXT DEFAULT '')
    RETURNS BOOLEAN AS $$
BEGIN

    INSERT INTO ALUGUEL_DETALHE(ID_ALUGUEL,cep,logradouro,bairro,descricao,data_hora,tipo)
    values (uuid(P_ID_ALUGUEL),P_CEP,P_LOGRADOURO,P_BAIRRO,P_DESCRICAO,P_DATA_HORA,P_TIPO);

    RETURN TRUE;

EXCEPTION WHEN OTHERS THEN
    PERFORM FN_REPORT_ERRO('ERRO AO SALVAR DETALHE DE ALUGUEL', SQLSTATE, SQLERRM, 'FN_SALVA_DETALHE_ALUGUEL', 'ALUGUEL_DETALHE', CURRENT_QUERY(),P_USUARIO);
    RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL;
