CREATE TABLE ALUGUEL_BAIXA(
    ID_BAIXA SERIAL PRIMARY KEY,
    ID_PAGAMENTO UUID REFERENCES RETORNO_MERCADO_PAGO(ID_PAGAMENTO),
    TIPO_TAXA INT,
    VALOR_SAQUE DECIMAL(20,2),
    DATA_SAQUE timestamptz,
    DATA_INCLUSAO timestamptz DEFAULT timezone('America/Sao_Paulo',current_timestamp),
    DATA_MODIFICACAO timestamptz
);