CREATE TABLE CATEGORIA(
	ID_CATEGORIA SERIAL,
	DESCRICAO TEXT,
	DATA_INCLUSAO TIMESTAMPTZ DEFAULT timezone('America/Sao_Paulo', CURRENT_TIMESTAMP),
	DATA_MODIFICACAO TIMESTAMPTZ,
	PRIMARY KEY(ID_CATEGORIA)
);
	
CREATE UNIQUE INDEX IX_TBL_CATEGORIA ON CATEGORIA (DESCRICAO);