CREATE TABLE TAXAS(
	ID_TAXA SERIAL,
	ID_TIPO_TAXA INT,
	VLR_TAXA DOUBLE PRECISION,
	DATA_INCLUSAO TIMESTAMPTZ DEFAULT timezone('America/Sao_Paulo', CURRENT_TIMESTAMP),
	DATA_MODIFICACAO TIMESTAMPTZ,
	PRIMARY KEY(ID_TAXA),
	FOREIGN KEY(ID_TIPO_TAXA) REFERENCES TIPO_TAXA
);

CREATE UNIQUE INDEX IX_TAXA ON TAXAS(ID_TIPO_TAXA, VLR_TAXA);