CREATE TABLE TIPO_TAXA(
	ID_TIPO_TAXA SERIAL,
	TIPO_TAXA TEXT NOT NULL,
	DATA_INCLUSAO TIMESTAMPTZ DEFAULT timezone('America/Sao_Paulo', CURRENT_TIMESTAMP),
	DATA_MODIFICACAO TIMESTAMPTZ,
	PRIMARY KEY(ID_TIPO_TAXA)
);

INSERT INTO TIPO_TAXA(TIPO_TAXA)VALUES('Taxa de aluguel da plataforma')